### ISSUE TITLE
your three party library don't use

### ISSUE THREAD

**Issue by lilitao00** [danielalves/BlurImageProcessor#5]
I want to use your three party library,but it don't use.  especially iterations paramter don't work....

**Comment by danielalves** [comment]
Hi @lilitao00!

I'm sorry, but I don't think I understand your question 😕 You're trying to say `BlurImageProcessor` doesn't work?

I don't know if you already tried it, but there's a [demo app](https://github.com/danielalves/BlurImageProcessor/tree/master/Demo) available in the repository. You can walk through its code to see how `BlurImageProcessor` can be used/works.

There's  also the `iterations` parameter [documentation](https://github.com/danielalves/BlurImageProcessor/blob/master/BlurImageProcessor/ALDBlurImageProcessor/ALDBlurImageProcessor.h#L108). Are you passing in a valid value (greater than `0`)? When you use `0`, the original image is returned, so it may give you the feeling that the component is not working. The same idea applies to the `radius` parameter. Check its documentation [here](https://github.com/danielalves/BlurImageProcessor/blob/master/BlurImageProcessor/ALDBlurImageProcessor/ALDBlurImageProcessor.h#L104).

Finally, the underlying Apple API used by `BlurImageProcessor` is still valid, as you [can see here](https://developer.apple.com/reference/accelerate/1515945-vimageboxconvolve_argb8888), so there shouldn't be any `deprecated` related issue. I don't know if a newer version of CocoaPods changed how things work, but [this line](https://github.com/danielalves/BlurImageProcessor/blob/master/BlurImageProcessor.podspec#L14) specifies that the `Acceleration` framework should be linked to your app. If it is not linked, the app shouldn't even compile. Anyway, this is also a good thing to check to ensure things are working nicely.

I hope the info above can help you!

**Comment by lilitao00** [comment]
The reason why I found the problem，because I use the image by test.png,but don't use test@2x.png. I don't known what is the difference between the two picture.

I have a task now, use screen capture do blurred.  I have to keep the screen capture save test@2x.png in local file,and use it,don't use directly;

For example:
- (UIImage *)getImage {
    
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(375/2, 667/2), NO, 1);  //NO，YES 控制是否透明
    [self.view.layer renderInContext:UIGraphicsGetCurrentContext()];
    UIImage *image = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    // 生成后的image
//    UIImage *image1 = [UIImage imageWithData:UIImageJPEGRepresentation(image, 1)];
    
    NSString * path = [NSString stringWithFormat:@"%@/Documents/4@2x.png", NSHomeDirectory()];
    ;
    [UIImageJPEGRepresentation(image, 1) writeToFile:path atomically:NO];
    // 读取
    NSString * path1 = [NSString stringWithFormat:@"%@/Documents/4@2x.png", NSHomeDirectory()];
    UIImage *image3 = [UIImage imageWithContentsOfFile:path1];
    
    return image3;
}

I don't know why image1 don't use...

**Comment by danielalves** [comment]
@lilitao00 Does `[UIImage imageWithData:UIImageJPEGRepresentation(image, 1)]` really returns a valid image? You can check the actual image it returns through the XCode debugger. 

The only difference I see between `image1` and `image3` is that `image1` is not saved to the disk before it is used. The code that is working **does** save it and then load it to `image3`. Besides that, I don't see a good reason for `BlurImageProcessor` to not work.

Anyway, your question made me realize that the Demo's Podfile was outdated, so I updated it. Thanks for that =)

**Comment by danielalves** [comment]
I ran the project and the Demo, everything seems to be working. Since I had no follow up, I'll be closing this issue.
